### ISSUE TITLE
Code Release 

### ISSUE THREAD

**Issue by abhigoku10** [wudongming97/Prompt4Driving#1]
@wencheng256 @wudongming97  thanks ffor sharing ur work, when r u planning to realase the code !!!
Thanks in advance

**Comment by wudongming97** [comment]
Hi @abhigoku10,

Sorry, our current plan is to release the dataset and model after the paper is accepted. Of course, we do not rule out the possibility of an early release. This requires further internal discussions. Thanks for your attention.

**Comment by abhigoku10** [comment]
@wudongming97  please do keep us posted on the work as it new and very innovative one

**Comment by wudongming97** [comment]
No problem!
