### ISSUE TITLE
About the release  of code and dataset

### ISSUE THREAD

**Issue by Rabbia-Hassan** [wudongming97/Prompt4Driving#2]
Hello !
Your work is amazing. I am interested in it. I request you to please tell when will you release the code and the dataset?
Thanks for your time

I look forward to your response
Regards
Rabbia Hassan

**Comment by wudongming97** [comment]
Hi, 
I am sorry that our current plan is to release the dataset and model after the paper is accepted. Of course, we do not rule out the possibility of an early release after internal discussions. Thanks for your attention.

**Comment by Rabbia-Hassan** [comment]
Thank you for the response. Can we expect any date or month of the release ? I mean any rough idea ? We are looking forward to use this path breaking dataset and code.
