### ISSUE TITLE
About manually collected data

### ISSUE THREAD

**Issue by haofuly** [wudongming97/Prompt4Driving#6]
Hi, @wudongming97 ,congratulations for the paper acceptation, and thanks for your good work.
I wonder that would the manually collected data be released, just like the step 2 of Fig.2 in paper，especially for Nuscenes?
For example, this instance token corresponds to the elements: {white, car, parked at roadside, ...}

**Comment by wudongming97** [comment]
Hi @haofuly,

The original prompt is also shown in each json file. We don't distinguish this from either manual annotation or automatic annotation. In general, the automatic annotations refer to object categories and object position, and the manual annotations refer to the remaining ones.

**Comment by haofuly** [comment]
Thanks for explaination, @wudongming97
But I noticed that the "original prompt" includes (1) text, such as 'truck' (2) unicode, such as '\u9ec4\u8272\u7684' (3) None.
Does (1) corresponds to automatic annotation and (2) corresponds to manual anno?

**Comment by wudongming97** [comment]
Yep!
